### ISSUE TITLE
Is there a reason using options instead of query parameters?

### ISSUE THREAD

**Issue by tiye** [unindented/remarkable-loader#1]
Before I found this loader the solution came to my mind is putting Remarkable options into the query, like:
http://webpack.github.io/docs/using-loaders.html#query-parameters

``` js
{
    test: /\.png$/,
    loader: "url-loader"
    query: { mimetype: "image/png" }
}
```

but instead I found this loader using a property called remarkable. Is solution better?

**Comment by unindented** [comment]
I tend to use `query` when there's only one or two options to set. If there are more than that, I prefer to have a separate hash of options.

The creator of webpack seems to follow a similar pattern. See for example `jshint-loader` (https://www.npmjs.com/package/jshint-loader). Options for that loader are passed in a property called `jshint`.

So I think it's not better or worse, it's just a matter of preference.
